--------------------------------------------------------------------------------
---------------------------------- SEQUENCE ------------------------------------
--------------------------------------------------------------------------------
--BUSINESS / STORE
DROP SEQUENCE SEQ_STORE;
CREATE SEQUENCE SEQ_STORE NOCACHE NOCYCLE;

DROP SEQUENCE SEQ_ST_ATTACHMENT;
CREATE SEQUENCE SEQ_ST_ATTACHMENT NOCACHE NOCYCLE;

DROP SEQUENCE SEQ_BUSINESS;
CREATE SEQUENCE SEQ_BUSINESS NOCACHE NOCYCLE;

DROP SEQUENCE SEQ_BP_ATTACHMENT;
CREATE SEQUENCE SEQ_BP_ATTACHMENT NOCACHE NOCYCLE;

DROP SEQUENCE SEQ_BUSINESS_HISTORY;
CREATE SEQUENCE SEQ_BUSINESS_HISTORY NOCACHE NOCYCLE;

--PROJECT
DROP SEQUENCE SEQ_PROJECT;
CREATE SEQUENCE SEQ_PROJECT NOCACHE NOCYCLE;

DROP SEQUENCE SEQ_PROJECT_MEMBER;
CREATE SEQUENCE SEQ_PROJECT_MEMBER NOCACHE NOCYCLE;

DROP SEQUENCE SEQ_PRJ_MEMO;
CREATE SEQUENCE SEQ_PRJ_MEMO NOCACHE NOCYCLE;

DROP SEQUENCE SEQ_MEMO_ATTACHMENT;
CREATE SEQUENCE SEQ_MEMO_ATTACHMENT NOCACHE NOCYCLE;

DROP SEQUENCE SEQ_MEMO_MEMBER;
CREATE SEQUENCE SEQ_MEMO_MEMBER NOCACHE NOCYCLE;

DROP SEQUENCE SEQ_MEMO_COMMENT;
CREATE SEQUENCE SEQ_MEMO_COMMENT NOCACHE NOCYCLE;

DROP SEQUENCE SEQ_PRIORITY;
CREATE SEQUENCE SEQ_PRIORITY NOCACHE NOCYCLE;

DROP SEQUENCE SEQ_PROJECT_KEY;
CREATE SEQUENCE SEQ_PROJECT_KEY NOCACHE NOCYCLE;

--MEMBER
DROP SEQUENCE SEQ_MEMBER;
CREATE SEQUENCE SEQ_MEMBER NOCACHE NOCYCLE;

DROP SEQUENCE SEQ_JOB;
CREATE SEQUENCE SEQ_JOB NOCACHE NOCYCLE;

DROP SEQUENCE SEQ_DEPT;
CREATE SEQUENCE SEQ_DEPT NOCACHE NOCYCLE;

DROP SEQUENCE SEQ_COMPANY;
CREATE SEQUENCE SEQ_COMPANY NOCACHE NOCYCLE;

DROP SEQUENCE SEQ_EMPLOYEE;
CREATE SEQUENCE SEQ_EMPLOYEE NOCACHE NOCYCLE;

--BOARD/ NOTICE
DROP SEQUENCE SEQ_NOTICE;
CREATE SEQUENCE SEQ_NOTICE NOCACHE NOCYCLE;

DROP SEQUENCE SEQ_NOTICE_ATTACHMENT;
CREATE SEQUENCE SEQ_NOTICE_ATTACHMENT NOCACHE NOCYCLE;

DROP SEQUENCE SEQ_BOARD_ATTACHMENT;
CREATE SEQUENCE SEQ_BOARD_ATTACHMENT NOCACHE NOCYCLE;

DROP SEQUENCE SEQ_BOARD_COMMENT;
CREATE SEQUENCE SEQ_BOARD_COMMENT NOCACHE NOCYCLE;

DROP SEQUENCE SEQ_BOARD;
CREATE SEQUENCE SEQ_BOARD NOCACHE NOCYCLE;

--SCHEDULE
DROP SEQUENCE SEQ_SCH_ATTACHMENT;
CREATE SEQUENCE SEQ_SCH_ATTACHMENT NOCACHE NOCYCLE;

DROP SEQUENCE SEQ_SCHEDULE;
CREATE SEQUENCE SEQ_SCHEDULE NOCACHE NOCYCLE;

DROP SEQUENCE SEQ_SCHEDULE_MEMBER;
CREATE SEQUENCE SEQ_SCHEDULE_MEMBER NOCACHE NOCYCLE;

DROP SEQUENCE SEQ_PHONE_RESERVATION;
CREATE SEQUENCE SEQ_PHONE_RESERVATION NOCACHE NOCYCLE;
--------------------------------------------------------------------------------
---------------------------------- FUCTION -------------------------------------
--------------------------------------------------------------------------------
-- BUSINESS FUNCTION
CREATE OR REPLACE FUNCTION GET_BP_ATTACHMENT_NO
RETURN NUMBER
AS
    N NUMBER;
BEGIN
    SELECT SEQ_BP_ATTACHMENT.NEXTVAL
    INTO N
    FROM DUAL;
    RETURN N;
END
;
/

-- STORE FUNCTION
CREATE OR REPLACE FUNCTION GET_ST_ATTACHMENT_NO
RETURN NUMBER
AS
    N NUMBER;
BEGIN
    SELECT SEQ_ST_ATTACHMENT.NEXTVAL
    INTO N
    FROM DUAL;
    RETURN N;
END
;
/

-- BOARD FUNCTION
CREATE OR REPLACE FUNCTION GET_BOARD_ATTACHMENT_NO
RETURN NUMBER
AS
  N NUMBER;
BEGIN

  SELECT SEQ_BOARD_ATTACHMENT.NEXTVAL
  INTO N
  FROM DUAL;
  
  RETURN N;
END;
/

-- NOTICE FUCTION
CREATE OR REPLACE FUNCTION GET_NOTICE_ATTACHMENT_NO
RETURN NUMBER
AS
  N NUMBER;
BEGIN

  SELECT SEQ_NOTICE_ATTACHMENT.NEXTVAL
  INTO N
  FROM DUAL;
  
  RETURN N;
END;
/
--------------------------------------------------------------------------------
--------------------------------- TRIGGER -------------------------------------
--------------------------------------------------------------------------------
-- 프로젝트 키값 트리거
DROP TRIGGER TRG_PROJECT_KEY;
CREATE OR REPLACE TRIGGER TRG_PROJECT_KEY
BEFORE 
    INSERT ON PROJECT
FOR EACH ROW
BEGIN
    :NEW.KEY := LPAD(SEQ_PROJECT_KEY.NEXTVAL, 4, '0');
END;
/

--MEMBER TRIGGER
CREATE OR REPLACE TRIGGER TRG_EMPLOYEE_INSERT
BEFORE INSERT ON EMPLOYEE
FOR EACH ROW
DECLARE
    max_seq NUMBER; -- 시퀀스 조정용
BEGIN
    -- 현재 테이블에서 가장 큰 EMP_NO 값을 가져옵니다.
    SELECT MAX(TO_NUMBER(SUBSTR(EMP_NO, 5))) INTO max_seq
    FROM EMPLOYEE
    WHERE EMP_NO LIKE '2401%';

    -- 시퀀스 값 초기화 (없으면 기본값 1로 설정)
    IF max_seq IS NULL THEN
        max_seq := 0;
    END IF;

    -- EMP_NO 자동 생성
    :NEW.EMP_NO := '2401' || LPAD(max_seq + 1, 2, '0');
END;
/
COMMIT;

--------------------------------------------------------------------------------
-------------------------- TABLE CREATE & DROP ---------------------------------
--------------------------------------------------------------------------------
--STORE/BUSINESS
DROP TABLE STORE CASCADE CONSTRAINTS;
CREATE TABLE STORE (
NO	        NUMBER		                NOT NULL PRIMARY KEY,
MANAGER_NO	NUMBER		                NOT NULL,
NAME	    VARCHAR2(30)		        NOT NULL,
CEO	        VARCHAR2(30)	        	NOT NULL,
BRN	        CHAR(10)		            NOT NULL,
START_DATE	CHAR(8)	                	NULL,
END_DATE	CHAR(8)	                	NULL,
ADDRESS	VARCHAR2(250)	        	NULL,
PHONE	    VARCHAR2(15)	          	NULL,
CEO_PHONE	CHAR(11)            		NULL,
DEL_YN	    CHAR(1)	    DEFAULT 'N' 	CHECK(DEL_YN IN('Y','N')),
ENROLL_DATE	TIMESTAMP	DEFAULT SYSDATE	NULL,
MODIFY_DATE	TIMESTAMP		            NULL,
EDU_DATE	CHAR(12)	            	NULL,
OPEN_DATE	CHAR(8)	                	NULL,
STATUS      VARCHAR2(20)                NULL,
CLOSE_DATE  CHAR(8)     DEFAULT '-'     NULL
);

DROP TABLE ST_ATTACHMENT CASCADE CONSTRAINTS;
CREATE TABLE ST_ATTACHMENT (
NO	        NUMBER		                NULL PRIMARY KEY,
REF_ST_NO	NUMBER		                NOT NULL,
ORIGIN_NAME	VARCHAR2(2000)		        NULL,
CHANGE_NAME	VARCHAR2(2000)      		NULL,
FILE_PATH	VARCHAR2(2000)	        	NULL,
STATUS	    CHAR(1) 	DEFAULT 'Y' 	NULL,
ENROLL_DATE	TIMESTAMP	DEFAULT SYSDATE	NULL
);

DROP TABLE BUSINESS CASCADE CONSTRAINTS;
CREATE TABLE BUSINESS (
NO	        NUMBER		                NOT NULL PRIMARY KEY,
MANAGER_NO	NUMBER	                	NOT NULL,
DEPT_NAME   VARCHAR(30)                 NOT NULL,
NAME	    VARCHAR2(30)	        	NOT NULL,
CEO	        VARCHAR2(20)        		NOT NULL,
BRN	        CHAR(10)            		NOT NULL,
BT_CODE	    CHAR(6)	                	NULL,
ADDRESS	    VARCHAR2(250)	        	NOT NULL,
PHONE	    CHAR(11)	            	NOT NULL,
DEL_YN	    CHAR(1)	    DEFAULT 'N' 	CHECK(DEL_YN IN('Y','N')),
ENROLL_DATE	TIMESTAMP	DEFAULT SYSDATE	NULL,
MODIFY_DATE	TIMESTAMP		            NULL
);

DROP TABLE BP_ATTACHMENT CASCADE CONSTRAINTS;
CREATE TABLE BP_ATTACHMENT (
NO      	NUMBER		                NULL PRIMARY KEY,
REF_BP_NO	NUMBER		                NOT NULL,
ORIGIN_NAME	VARCHAR2(2000)	        	NULL,
CHANGE_NAME	VARCHAR2(2000)	        	NULL,
FILE_PATH	VARCHAR2(2000)	        	NULL,
STATUS	    CHAR(1)	    DEFAULT 'Y'	    NULL,
ENROLL_DATE	TIMESTAMP	DEFAULT SYSDATE	NULL
);

DROP TABLE BUSINESS_HISTORY CASCADE CONSTRAINTS;
CREATE TABLE BUSINESS_HISTORY (
NO          NUMBER                      NOT NULL PRIMARY KEY,
BP_NO       NUMBER                      NOT NULL,
START_DATE  CHAR(8)                     NOT NULL,
END_DATE    CHAR(8)                     NULL
);

--PROJECT 
DROP TABLE PROJECT CASCADE CONSTRAINTS;
CREATE TABLE PROJECT (
KEY     	CHAR(4)		                NOT NULL PRIMARY KEY,
WRITER_NO	NUMBER		                NOT NULL,
PRIORITY    NUMBER                      NOT NULL,
NAME	    VARCHAR2(50)		        NULL,
START_DATE	CHAR(8)		                NULL,
END_DATE	CHAR(8)		                NULL,
ENROLL_DATE	TIMESTAMP	DEFAULT SYSDATE	NULL,
MODIFY_DATE	TIMESTAMP		            NULL,
DEL_YN	    CHAR(1)	    DEFAULT 'N' 	NULL,
DISCLOSURE  VARCHAR2(20)                NULL
);

DROP TABLE PROJECT_MEMBER CASCADE CONSTRAINTS;
CREATE TABLE PROJECT_MEMBER (
NO	        NUMBER		                NOT NULL PRIMARY KEY,
PRJ_KEY     CHAR(4)	                	NOT NULL,
EMP_NO  	NUMBER	                	NOT NULL,
MODI_AUTH	VARCHAR2(10)	    DEFAULT '수정' 	NULL
);

DROP TABLE PRJ_MEMO CASCADE CONSTRAINTS;
CREATE TABLE PRJ_MEMO (
NO	        NUMBER		                NOT NULL PRIMARY KEY,
PRJ_KEY	    CHAR(4)		                NOT NULL,
WRITER_NO   NUMBER		                NOT NULL,
BP_NO	    NUMBER	                	NULL,
ST_NO	    NUMBER		                NULL,
PRIORITY    NUMBER                      NOT NULL,
NAME	    VARCHAR2(20)		        NULL,
CONTENT	    VARCHAR2(1000)	        	NULL,
ING	        VARCHAR2(20)		        NULL,
START_DATE	CHAR(8)		                NULL,
END_DATE	CHAR(8)	                	NULL,
ENROLL_DATE	TIMESTAMP	DEFAULT SYSDATE	NULL,
MODIFY_DATE	TIMESTAMP	            	NULL,
DEL_YN	    CHAR(1)	    DEFAULT 'N' 	NULL
);

DROP TABLE MEMO_MEMBER CASCADE CONSTRAINTS;
CREATE TABLE MEMO_MEMBER (
NO	        NUMBER		                NOT NULL PRIMARY KEY,
MEMO_KEY	NUMBER	                	NOT NULL,
EMP_NO	    NUMBER	                	NOT NULL,
MODI_AUTH	VARCHAR2(10)	    DEFAULT '수정' 	NULL
);

DROP TABLE MEMO_ATTACHMENT CASCADE CONSTRAINTS;
CREATE TABLE MEMO_ATTACHMENT (
NO	        NUMBER		                NULL PRIMARY KEY,
REF_NO  	NUMBER	                	NOT NULL,
ORIGIN_NAME	VARCHAR2(2000)	        	NULL,
CHANGE_NAME	VARCHAR2(2000)      		NULL,
FILE_PATH	VARCHAR2(2000)	DEFAULT 'Y'	NULL,
STATUS	    CHAR(1)	                	NULL,
ENROLL_DATE	TIMESTAMP	              	NULL
);

DROP TABLE MEMO_COMMENT CASCADE CONSTRAINTS;
CREATE TABLE MEMO_COMMENT (
NO          NUMBER                      NULL PRIMARY KEY,
MEMO_NO     NUMBER                      NOT NULL,
WRI_NO      NUMBER                      NOT NULL,
CONTENT     VARCHAR2(500)               NULL,
ENROLL_DATE TIMESTAMP   DEFAULT SYSDATE NULL,
MODIFY_DATE TIMESTAMP                   NULL
);

DROP TABLE PRIORITY CASCADE CONSTRAINTS;
CREATE TABLE PRIORITY (
NO	        NUMBER		                NOT NULL PRIMARY KEY,
NAME	    VARCHAR2(6)		                NULL
);

--MEMBER
DROP TABLE EMPLOYEE CASCADE CONSTRAINTS;
CREATE TABLE EMPLOYEE (
EMP_NO      NUMBER		                    NOT NULL PRIMARY KEY,
CP_CODE	    CHAR(4)		                    NOT NULL,
JOB_CODE	NUMBER		                    NOT NULL,
DEPT_CODE	NUMBER	                	    NOT NULL,
START_TIME	TIMESTAMP                       NULL,
FINISH_DATE	TIMESTAMP		                NULL,
HIRE_DATE	CHAR(8)	    DEFAULT SYSDATE     NULL,
QUIT_DATE	CHAR(8)		                    NULL,
QUIT_YN	    CHAR(1)     DEFAULT 'N' 	    NULL
);

DROP TABLE MEMBER CASCADE CONSTRAINTS;
CREATE TABLE MEMBER (
NO	        NUMBER		                NOT NULL PRIMARY KEY,
ID  	    NUMBER		                NOT NULL,
NAME	    VARCHAR2(20)		        NOT NULL,
PWD	        VARCHAR2(300)		        NOT NULL,
NICK	    VARCHAR2(20)		        NULL,
ID_NUM	    CHAR(13)		            NOT NULL,
GENDER	    CHAR(1)		                NOT NULL,
PHONE	    CHAR(11)	            	NULL,
EMAIL	    VARCHAR2(50)	        	NULL,
ADDRESS	    VARCHAR2(200)       		NULL,
PROFILE	    VARCHAR2(1000)	        	NULL
);


DROP TABLE COMPANY CASCADE CONSTRAINTS;
CREATE TABLE COMPANY (
CP_CODE	    CHAR(4)		                NOT NULL PRIMARY KEY,
CP_NAME	    VARCHAR2(20)	            NOT NULL
);

DROP TABLE JOB CASCADE CONSTRAINTS;
CREATE TABLE JOB (
JOB_CODE    NUMBER                      NOT NULL PRIMARY KEY,
JOB_NAME    VARCHAR2(20)                NOT NULL
);

DROP TABLE DEPT CASCADE CONSTRAINTS;
CREATE TABLE DEPT (
DEPT_CODE   NUMBER                      NOT NULL PRIMARY KEY,
DEPT_NAME   VARCHAR2(20)                NOT NULL
);

--BOARD/NOTICE
DROP TABLE NOTICE CASCADE CONSTRAINTS;
CREATE TABLE NOTICE (
    NO              NUMBER              NOT NULL PRIMARY KEY,
    WRITER_NO       NUMBER              NOT NULL,
    TITLE           VARCHAR2(100)       NOT NULL,
    CONTENT         VARCHAR2(2000)      NULL,
    URGENT_YN       CHAR(1)     DEFAULT 'N'     NULL,
    HIT             NUMBER      DEFAULT 0       NULL,
    ENROLL_DATE     TIMESTAMP   DEFAULT SYSDATE NULL,
    MODIFY_DATE     TIMESTAMP               NULL,
    DEL_YN          CHAR(1)     DEFAULT 'N'    NULL
);

DROP TABLE NOTICE_ATTACHMENT CASCADE CONSTRAINTS;
CREATE TABLE NOTICE_ATTACHMENT (
    NO              NUMBER              NULL PRIMARY KEY,
    REF_NOTI_NO     NUMBER              NOT NULL,
    ORIGIN_NAME     VARCHAR2(100)       NULL,
    CHANGE_NAME     VARCHAR2(2000)      NULL,
    FILE_PATH       VARCHAR2(2000)      NULL,
    STATUS          CHAR(1)     DEFAULT 'Y'     NULL,
    ENROLL_DATE     TIMESTAMP   DEFAULT SYSDATE NULL
);

DROP TABLE BOARD CASCADE CONSTRAINTS;
CREATE TABLE BOARD (
    NO              NUMBER              NULL PRIMARY KEY,
    WRITER_NO       NUMBER              NOT NULL,
    TITLE           VARCHAR2(100)       NOT NULL,
    CONTENT         VARCHAR2(2000)      NULL,
    ENROLL_DATE     TIMESTAMP   DEFAULT SYSDATE NULL,
    MODIFY_DATE     TIMESTAMP           NULL,
    HIT             NUMBER      DEFAULT 0       NULL,
    DEL_YN          CHAR(1)     DEFAULT 'N'    NULL
);

DROP TABLE BOARD_ATTACHMENT CASCADE CONSTRAINTS;
CREATE TABLE BOARD_ATTACHMENT (
    NO              NUMBER              NULL PRIMARY KEY,
    REF_BOARD_NO    NUMBER              NOT NULL,
    ORIGIN_NAME     VARCHAR2(2000)      NULL,
    CHANGE_NAME     VARCHAR2(2000)      NULL,
    FILE_PATH       VARCHAR2(2000)      NULL,
    STATUS          CHAR(1)     DEFAULT 'Y'     NULL,
    ENROLL_DATE     TIMESTAMP   DEFAULT SYSDATE NULL
);

DROP TABLE BOARD_COMMENT CASCADE CONSTRAINTS;
CREATE TABLE BOARD_COMMENT (
    NO              NUMBER              NULL PRIMARY KEY,
    BOARD_NO        NUMBER              NULL,
    COM_WRI_NO      NUMBER              NOT NULL,
    CONTENT         VARCHAR2(500)       NULL,
    ENROLL_DATE     TIMESTAMP   DEFAULT SYSDATE NULL,
    MODIFY_DATE     TIMESTAMP           NULL
);

--SCHEDULE
DROP TABLE SCHEDULE CASCADE CONSTRAINTS;
CREATE TABLE SCHEDULE(
    NO              NUMBER                      NOT NULL PRIMARY KEY
    , WRITER_NO     NUMBER                      NOT NULL
    , MEMO_NO       NUMBER
    , BUSINESS_NO   NUMBER
    , BUSIHIS_NO    NUMBER
    , STORE_NO      NUMBER
    , PRIORITY      NUMBER      DEFAULT 2
    , TITLE         VARCHAR2(50)                NOT NULL
    , CONTENT       VARCHAR2(500)
    , LOCATION      VARCHAR2(200)               NULL
    , START_DATE    CHAR(10)                    NOT NULL
    , FINISH_DATE   CHAR(10)                    NOT NULL
    , START_TIME    CHAR(5)
    , FINISH_TIME   CHAR(5)
    , ALLDAY        CHAR(1)     DEFAULT 'N' CHECK(ALLDAY IN('Y', 'N'))
    , SHARE_YN      CHAR(1)     DEFAULT 'N' CHECK(SHARE_YN IN('Y','N'))
    , DEL_YN        CHAR(1)     DEFAULT 'N' CHECK(DEL_YN IN('Y','N'))
);

DROP TABLE SCHEDULE_MEMBER CASCADE CONSTRAINTS;
CREATE TABLE SCHEDULE_MEMBER (
    NO	            NUMBER		                NOT NULL PRIMARY KEY
    , SCH_NO	    NUMBER	                	NOT NULL
    , EMP_NO	    NUMBER		                NOT NULL
    , MODI_AUTH	    CHAR(1)	    DEFAULT 'N'	CHECK(MODI_AUTH IN('Y','N'))
);

DROP TABLE SCH_ATTACHMENT CASCADE CONSTRAINTS;
CREATE TABLE SCH_ATTACHMENT (
    NO	            NUMBER		                NULL PRIMARY KEY
    , REF_NO	    NUMBER		                NOT NULL
    , ORIGIN_NAME	VARCHAR2(2000)
    , CHANGE_NAME	VARCHAR2(2000)
    , FILE_PATH 	VARCHAR2(2000)
    , STATUS	    CHAR(1) 	DEFAULT 'Y'
    , ENROLL_DATE	TIMESTAMP	DEFAULT SYSDATE
);

DROP TABLE PHONE_RESERVATION CASCADE CONSTRAINTS;
CREATE TABLE PHONE_RESERVATION (
    NO	            NUMBER		                    NOT NULL PRIMARY KEY
    , WRITER_NO     NUMBER                          NOT NULL
    , CP_CODE	    CHAR(4)		                    NOT NULL
    , RDATE         CHAR(10)                        NOT NULL
    , RTIME	        CHAR(5)		                    NOT NULL
    , PHONE	        CHAR(11)                        NOT NULL
    , TITLE         VARCHAR2(500)                   NOT NULL
    , CONTENT       VARCHAR2(1000)                  NOT NULL
    , ENROLL_DATE   TIMESTAMP   DEFAULT SYSDATE
    , MODIFY_DATE   TIMESTAMP
    , DEL_YN        CHAR(1)     DEFAULT 'N' CHECK(DEL_YN IN('Y','N'))
);
--------------------------------------------------------------------------------
--------------------------------- COMMENT --------------------------------------
--------------------------------------------------------------------------------
--business/store
COMMENT ON COLUMN BP_ATTACHMENT.NO IS '거래처첨부고유번호';
COMMENT ON COLUMN BP_ATTACHMENT.REF_BP_NO IS '거래처번호';
COMMENT ON COLUMN BP_ATTACHMENT.ORIGIN_NAME IS '원본파일명';
COMMENT ON COLUMN BP_ATTACHMENT.CHANGE_NAME IS '수정파일명';
COMMENT ON COLUMN BP_ATTACHMENT.FILE_PATH IS '파일경로';
COMMENT ON COLUMN BP_ATTACHMENT.STATUS IS '파일상태';
COMMENT ON COLUMN BP_ATTACHMENT.ENROLL_DATE IS '업로드일시';

COMMENT ON COLUMN BUSINESS_HISTORY.NO IS '거래고유번호';
COMMENT ON COLUMN BUSINESS_HISTORY.BP_NO IS '거래처 번호';
COMMENT ON COLUMN BUSINESS_HISTORY.START_DATE IS '거래시작일';
COMMENT ON COLUMN BUSINESS_HISTORY.END_DATE IS '거래종료일';

COMMENT ON COLUMN BUSINESS.NO IS '거래처 번호';
COMMENT ON COLUMN BUSINESS.MANAGER_NO IS '담당자 사번';
COMMENT ON COLUMN BUSINESS.NAME IS '거래처명';
COMMENT ON COLUMN BUSINESS.CEO IS '대표자명';
COMMENT ON COLUMN BUSINESS.BRN IS '사업자등록번호';
COMMENT ON COLUMN BUSINESS.BT_CODE IS '업태코드';
COMMENT ON COLUMN BUSINESS.ADDRESS IS '거래처 주소';
COMMENT ON COLUMN BUSINESS.PHONE IS '거래처 전화번호';
COMMENT ON COLUMN BUSINESS.DEL_YN IS '삭제여부';
COMMENT ON COLUMN BUSINESS.ENROLL_DATE IS '작성일';
COMMENT ON COLUMN BUSINESS.MODIFY_DATE IS '수정일';

COMMENT ON COLUMN STORE.NO IS '가맹점 번호';
COMMENT ON COLUMN STORE.MANAGER_NO IS '담당자 사번';
COMMENT ON COLUMN STORE.NAME IS '가맹점명';
COMMENT ON COLUMN STORE.CEO IS '가맹점주명';
COMMENT ON COLUMN STORE.BRN IS '사업자등록번호';
COMMENT ON COLUMN STORE.START_DATE IS '계약 시작일';
COMMENT ON COLUMN STORE.END_DATE IS '계약 종료일';
COMMENT ON COLUMN STORE.ADDRESS IS '가맹점 주소';
COMMENT ON COLUMN STORE.PHONE IS '가맹점 전화번호';
COMMENT ON COLUMN STORE.CEO_PHONE IS '가맹점장 전화번호';
COMMENT ON COLUMN STORE.DEL_YN IS '가맹점 삭제여부';
COMMENT ON COLUMN STORE.ENROLL_DATE IS '작성일';
COMMENT ON COLUMN STORE.MODIFY_DATE IS '수정일';
COMMENT ON COLUMN STORE.EDU_DATE IS '교육일자';
COMMENT ON COLUMN STORE.OPEN_DATE IS '오픈일';
COMMENT ON COLUMN STORE.CLOSE_DATE IS '폐업일';
COMMENT ON COLUMN STORE.STATUS IS '오픈 상태';

COMMENT ON COLUMN ST_ATTACHMENT.NO IS '가맹점첨부고유번호';
COMMENT ON COLUMN ST_ATTACHMENT.REF_ST_NO IS '가맹점 번호';
COMMENT ON COLUMN ST_ATTACHMENT.ORIGIN_NAME IS '원본파일명';
COMMENT ON COLUMN ST_ATTACHMENT.CHANGE_NAME IS '수정파일명';
COMMENT ON COLUMN ST_ATTACHMENT.FILE_PATH IS '파일경로';
COMMENT ON COLUMN ST_ATTACHMENT.STATUS IS '파일상태';
COMMENT ON COLUMN ST_ATTACHMENT.ENROLL_DATE IS '업로드일시';

--project
COMMENT ON COLUMN MEMO_COMMENT.WRI_NO IS '메모 댓글 작성자 사번';
COMMENT ON COLUMN MEMO_MEMBER.EMP_NO IS '추가 사원';
COMMENT ON COLUMN PROJECT_MEMBER.EMP_NO IS '추가 사원';
COMMENT ON COLUMN PROJECT.ACCESS_LEVEL IS '편집권한 레벨';
COMMENT ON COLUMN PROJECT.DISCLOSURE IS '공개범위';

--Notice / Board
COMMENT ON COLUMN BOARD.NO IS '게시글 번호';
COMMENT ON COLUMN BOARD.WRITER_NO IS '작성자 사번';
COMMENT ON COLUMN BOARD.TITLE IS '게시글 제목';
COMMENT ON COLUMN BOARD.CONTENT IS '게시글 내용';
COMMENT ON COLUMN BOARD.ENROLL_DATE IS '등록일';
COMMENT ON COLUMN BOARD.MODIFY_DATE IS '수정일';
COMMENT ON COLUMN BOARD.HIT IS '조회수';
COMMENT ON COLUMN BOARD.DEL_YN IS '삭제여부';

COMMENT ON COLUMN NOTICE.NO IS '공지사항 번호';
COMMENT ON COLUMN NOTICE.WRITER_NO IS '작성자 사번';
COMMENT ON COLUMN NOTICE.TITLE IS '공지 제목';
COMMENT ON COLUMN NOTICE.CONTENT IS '공지 내용';
COMMENT ON COLUMN NOTICE.URGENT_YN IS '긴급/일반(긴급일 때 Y)';
COMMENT ON COLUMN NOTICE.HIT IS '조회수';
COMMENT ON COLUMN NOTICE.ENROLL_DATE IS '등록일';
COMMENT ON COLUMN NOTICE.MODIFY_DATE IS '수정일';
COMMENT ON COLUMN NOTICE.DEL_YN IS '삭제여부';

COMMENT ON COLUMN BOARD_COMMENT.NO IS '게시글댓글번호';
COMMENT ON COLUMN BOARD_COMMENT.BOARD_NO IS '게시글번호';
COMMENT ON COLUMN BOARD_COMMENT.COM_WRI_NO IS '댓글 작성자 사번';
COMMENT ON COLUMN BOARD_COMMENT.CONTENT IS '댓글내용';
COMMENT ON COLUMN BOARD_COMMENT.ENROLL_DATE IS '댓글 등록일';
COMMENT ON COLUMN BOARD_COMMENT.MODIFY_DATE IS '댓글 수정일';

COMMENT ON COLUMN NOTICE_ATTACHMENT.NO IS '공지첨부고유번호';
COMMENT ON COLUMN NOTICE_ATTACHMENT.REF_NOTI_NO IS '공지번호';
COMMENT ON COLUMN NOTICE_ATTACHMENT.ORIGIN_NAME IS '원본파일명';
COMMENT ON COLUMN NOTICE_ATTACHMENT.CHANGE_NAME IS '수정파일명';
COMMENT ON COLUMN NOTICE_ATTACHMENT.FILE_PATH IS '파일경로';
COMMENT ON COLUMN NOTICE_ATTACHMENT.STATUS IS '파일상태';
COMMENT ON COLUMN NOTICE_ATTACHMENT.ENROLL_DATE IS '업로드일시';

COMMENT ON COLUMN BOARD_ATTACHMENT.NO IS '게시글첨부고유번호';
COMMENT ON COLUMN BOARD_ATTACHMENT.REF_BOARD_NO IS '게시판번호';
COMMENT ON COLUMN BOARD_ATTACHMENT.ORIGIN_NAME IS '원본파일명';
COMMENT ON COLUMN BOARD_ATTACHMENT.CHANGE_NAME IS '수정파일명';
COMMENT ON COLUMN BOARD_ATTACHMENT.FILE_PATH IS '파일경로';
COMMENT ON COLUMN BOARD_ATTACHMENT.STATUS IS '파일상태';
COMMENT ON COLUMN BOARD_ATTACHMENT.ENROLL_DATE IS '업로드일시';
--------------------------------------------------------------------------------
------------------------------- FOREIGN KEY ------------------------------------
--------------------------------------------------------------------------------
-- business/ store
ALTER TABLE BUSINESS_HISTORY ADD CONSTRAINT FK_BUSINESS_TO_BUSINESS_HISTORY_1 FOREIGN KEY (BP_NO) REFERENCES BUSINESS (NO);
ALTER TABLE BUSINESS ADD CONSTRAINT FK_EMPLOYEE_TO_BUSINESS_1 FOREIGN KEY (MANAGER_NO) REFERENCES EMPLOYEE (EMP_NO);
ALTER TABLE BP_ATTACHMENT ADD CONSTRAINT FK_BUSINESS_TO_BP_ATTACHMENT_1 FOREIGN KEY (REF_BP_NO) REFERENCES BUSINESS (NO);
ALTER TABLE ST_ATTACHMENT ADD CONSTRAINT FK_STORE_TO_ST_ATTACHMENT_1 FOREIGN KEY (REF_ST_NO) REFERENCES STORE (NO);
ALTER TABLE STORE ADD CONSTRAINT FK_EMPLOYEE_TO_STORE_1 FOREIGN KEY (MANAGER_NO) REFERENCES EMPLOYEE (EMP_NO);

-- project
ALTER TABLE PROJECT ADD CONSTRAINT FK_EMPLOYEE_TO_PROJECT_1 FOREIGN KEY (WRITER_NO) REFERENCES EMPLOYEE (EMP_NO);
ALTER TABLE PROJECT_MEMBER ADD CONSTRAINT FK_PROJECT_TO_PROJECT_MEMBER_1 FOREIGN KEY (PRJ_KEY) REFERENCES PROJECT (KEY);
ALTER TABLE PROJECT_MEMBER ADD CONSTRAINT FK_EMPLOYEE_TO_PROJECT_MEMBER_1 FOREIGN KEY (EMP_NO) REFERENCES EMPLOYEE (EMP_NO);
ALTER TABLE MEMO_MEMBER ADD CONSTRAINT FK_PRJ_MEMO_TO_MEMO_MEMBER_1 FOREIGN KEY (MEMO_KEY) REFERENCES PRJ_MEMO (NO);
ALTER TABLE MEMO_MEMBER ADD CONSTRAINT FK_EMPLOYEE_TO_MEMO_MEMBER_1 FOREIGN KEY (EMP_NO) REFERENCES EMPLOYEE (EMP_NO);
ALTER TABLE MEMO_ATTACHMENT ADD CONSTRAINT FK_PRJ_MEMO_TO_MEMO_ATTACHMENT_1 FOREIGN KEY (REF_MEMO_NO) REFERENCES PRJ_MEMO (NO);
ALTER TABLE MEMO_COMMENT ADD CONSTRAINT FK_PRJ_MEMO_TO_MEMO_COMMENT_1 FOREIGN KEY (MEMO_NO) REFERENCES PRJ_MEMO (NO);
ALTER TABLE MEMO_COMMENT ADD CONSTRAINT FK_EMPLOYEE_TO_MEMO_COMMENT_1 FOREIGN KEY (WRI_NO) REFERENCES EMPLOYEE (EMP_NO);
ALTER TABLE PRJ_MEMO ADD CONSTRAINT FK_PROJECT_TO_PRJ_MEMO_1 FOREIGN KEY (PRJ_KEY) REFERENCES PROJECT (KEY);
ALTER TABLE PRJ_MEMO ADD CONSTRAINT FK_EMPLOYEE_TO_PRJ_MEMO_1 FOREIGN KEY (WRITER_NO) REFERENCES EMPLOYEE (EMP_NO);
ALTER TABLE PRJ_MEMO ADD CONSTRAINT FK_BUSINESS_TO_PRJ_MEMO_1 FOREIGN KEY (BP_NO) REFERENCES BUSINESS (NO);
ALTER TABLE PRJ_MEMO ADD CONSTRAINT FK_STORE_TO_PRJ_MEMO_1 FOREIGN KEY (ST_NO) REFERENCES STORE (NO);

--Board/Notice
ALTER TABLE NOTICE ADD CONSTRAINT FK_EMPLOYEE_TO_NOTICE_1 FOREIGN KEY (WRITER_NO) REFERENCES EMPLOYEE (EMP_NO);
ALTER TABLE NOTICE_ATTACHMENT ADD CONSTRAINT FK_NOTICE_TO_NOTICE_ATTACHMENT_1 FOREIGN KEY (REF_NOTI_NO) REFERENCES NOTICE (NO);
ALTER TABLE BOARD ADD CONSTRAINT FK_EMPLOYEE_TO_BOARD_1 FOREIGN KEY (WRITER_NO) REFERENCES EMPLOYEE (EMP_NO);
ALTER TABLE BOARD_ATTACHMENT ADD CONSTRAINT FK_BOARD_TO_BOARD_ATTACHMENT_1 FOREIGN KEY (REF_BOARD_NO) REFERENCES BOARD (NO);
ALTER TABLE BOARD_COMMENT ADD CONSTRAINT FK_BOARD_TO_BOARD_COMMENT_1 FOREIGN KEY (BOARD_NO) REFERENCES BOARD (NO);
ALTER TABLE BOARD_COMMENT ADD CONSTRAINT FK_EMPLOYEE_TO_BOARD_COMMENT_1 FOREIGN KEY (COM_WRI_NO) REFERENCES EMPLOYEE (EMP_NO);
