--------------------------------------------------------------------------------
--------------------------------- BUSINESS -------------------------------------
--------------------------------------------------------------------------------
INSERT INTO BUSINESS (NO,MANAGER_NO,DEPT_NAME,NAME,CEO,BRN,BT_CODE,ADDRESS,PHONE)
VALUES(SEQ_BUSINESS.NEXTVAL,240103,'영업부','cv물류','홍길동','1254812354','110100','경기 성남시 분당구 고기로 25','01098765432');

INSERT INTO BUSINESS_HISTORY(NO,BP_NO,START_DATE,END_DATE) 
VALUES (SEQ_BUSINESS_HISTORY.NEXTVAL,SEQ_BUSINESS.CURRVAL,'12.10.10','11.01.31');

INSERT INTO BUSINESS (NO,MANAGER_NO,DEPT_NAME,NAME,CEO,BRN,BT_CODE,ADDRESS,PHONE)
VALUES(SEQ_BUSINESS.NEXTVAL,240109,'물류부','cv식품','박승우','4554812354','110240','경기 성남시 분당구 고기로 25','01098765432');

INSERT INTO BUSINESS_HISTORY(NO,BP_NO,START_DATE,END_DATE) 
VALUES (SEQ_BUSINESS_HISTORY.NEXTVAL,SEQ_BUSINESS.CURRVAL,'12.01.01','10.10.31');

INSERT INTO BUSINESS (NO,MANAGER_NO,DEPT_NAME,NAME,CEO,BRN,BT_CODE,ADDRESS,PHONE)
VALUES(SEQ_BUSINESS.NEXTVAL,240101,'인사부','해바라기','홍수철','7894812354','110240','경기 성남시 분당구 고기로 25','01098765432');

INSERT INTO BUSINESS_HISTORY(NO,BP_NO,START_DATE,END_DATE) 
VALUES (SEQ_BUSINESS_HISTORY.NEXTVAL,SEQ_BUSINESS.CURRVAL,'12.01.01','10.10.31');

INSERT INTO BUSINESS (NO,MANAGER_NO,DEPT_NAME,NAME,CEO,BRN,BT_CODE,ADDRESS,PHONE)
VALUES(SEQ_BUSINESS.NEXTVAL,240115,'총무부','코스모스','코스모','7894812354','110240','경기 성남시 분당구 고기로 25','01098765432');

INSERT INTO BUSINESS_HISTORY(NO,BP_NO,START_DATE,END_DATE) 
VALUES (SEQ_BUSINESS_HISTORY.NEXTVAL,SEQ_BUSINESS.CURRVAL,'12.01.01','10.10.31');

--------------------------------------------------------------------------------
----------------------------------- STORE --------------------------------------
--------------------------------------------------------------------------------
INSERT INTO STORE (NO,MANAGER_NO,NAME,CEO,BRN,START_DATE,END_DATE,ADDRESS,PHONE,CEO_PHONE,ENROLL_DATE,EDU_DATE,OPEN_DATE,STATUS)
VALUES(SEQ_STORE.NEXTVAL,240101,'종로 1점','차은우','0123456789','24.12.12','25.12.12','경기 성남시 분당구 고기로 25','021589645','01012345678',SYSDATE,'27.15.15','24.19.19','영업중');

INSERT INTO STORE (NO,MANAGER_NO,NAME,CEO,BRN,START_DATE,END_DATE,ADDRESS,PHONE,CEO_PHONE,ENROLL_DATE,EDU_DATE,OPEN_DATE,STATUS)
VALUES(SEQ_STORE.NEXTVAL,240105,'수지 1점','홍석천','0123456789','24.12.12','25.12.12','경기 성남시 분당구 고기로 25','021589645','01012345678',SYSDATE,'27.15.15','24.19.19','영업 준비중');

INSERT INTO STORE (NO,MANAGER_NO,NAME,CEO,BRN,START_DATE,END_DATE,ADDRESS,PHONE,CEO_PHONE,ENROLL_DATE,EDU_DATE,OPEN_DATE,STATUS)
VALUES(SEQ_STORE.NEXTVAL,240111,'분당 1점','김수현','0123456789','24.12.12','25.12.12','경기 성남시 분당구 고기로 25','021589645','01012345678',SYSDATE,'27.15.15','24.19.19','휴업중');

INSERT INTO STORE (NO,MANAGER_NO,NAME,CEO,BRN,START_DATE,END_DATE,ADDRESS,PHONE,CEO_PHONE,ENROLL_DATE,EDU_DATE,OPEN_DATE,STATUS)
VALUES(SEQ_STORE.NEXTVAL,240109,'성남 1점','김남길','0123456789','24.12.12','25.12.12','경기 성남시 분당구 고기로 25','021589645','01012345678',SYSDATE,'27.15.15','24.19.19','폐업');

--------------------------------------------------------------------------------
--------------------------------- PROJECT --------------------------------------
--------------------------------------------------------------------------------
INSERT INTO PROJECT(WRITER_NO, PRIORITY  , NAME , START_DATE , END_DATE, DISCLOSURE) VALUES (240101,  1 , '감자' , '20241201' , '20241210' , '전체공개');
INSERT INTO PROJECT(WRITER_NO, PRIORITY  , NAME , START_DATE , END_DATE, DISCLOSURE) VALUES (240101 , 1 , '고구마' , '20241201' , '20241210', '전체공개');
INSERT INTO PROJECT(WRITER_NO, PRIORITY  , NAME , START_DATE , END_DATE, DISCLOSURE) VALUES (240101 , 1 , '무말랭이' , '20241205' , '20241220', '전체공개');
INSERT INTO PROJECT(WRITER_NO, PRIORITY  , NAME , START_DATE , END_DATE, DISCLOSURE) VALUES (240101 , 2 , '호박' , '20241205' , '20241225', '전체공개');
INSERT INTO PROJECT(WRITER_NO, PRIORITY  , NAME , START_DATE , END_DATE, DISCLOSURE) VALUES (240101 , 2 , '오이' , '20241210' , '20241225', '비공개');
INSERT INTO PROJECT(WRITER_NO, PRIORITY  , NAME , START_DATE , END_DATE, DISCLOSURE) VALUES (240101 , 2 , '김밥' , '20241221' , '20241230', '비공개');
INSERT INTO PROJECT(WRITER_NO, PRIORITY  , NAME , START_DATE , END_DATE, DISCLOSURE) VALUES (240101 , 3 , '참치' , '20241222' , '20241207', '부서공개');
INSERT INTO PROJECT(WRITER_NO, PRIORITY  , NAME , START_DATE , END_DATE, DISCLOSURE) VALUES (240101 , 3 , '멸치' , '20241220' , '20241228', '부서공개');
INSERT INTO PROJECT(WRITER_NO, PRIORITY  , NAME , START_DATE , END_DATE, DISCLOSURE) VALUES (240101 , 3 , '김치' , '20241225' , '20241229', '부서공개');
INSERT INTO PROJECT(WRITER_NO, PRIORITY  , NAME , START_DATE , END_DATE, DISCLOSURE) VALUES (240101 , 3 , '붕어빵' , '20241230' , '20241231', '부서공개');

--------------------------------------------------------------------------------
-------------------------- PROJECT-MEMBER --------------------------------------
--------------------------------------------------------------------------------
INSERT INTO PROJECT_MEMBER(NO, PRJ_KEY, EMP_NO, MODI_AUTH) VALUES (SEQ_PROJECT_MEMBER.NEXTVAL, '0001', 240102, '수정');
INSERT INTO PROJECT_MEMBER(NO, PRJ_KEY, EMP_NO, MODI_AUTH) VALUES (SEQ_PROJECT_MEMBER.NEXTVAL, '0001', 240103, '수정');
INSERT INTO PROJECT_MEMBER(NO, PRJ_KEY, EMP_NO, MODI_AUTH) VALUES (SEQ_PROJECT_MEMBER.NEXTVAL, '0001', 240104, '읽기');
INSERT INTO PROJECT_MEMBER(NO, PRJ_KEY, EMP_NO, MODI_AUTH) VALUES (SEQ_PROJECT_MEMBER.NEXTVAL, '0001', 240105, '읽기');
INSERT INTO PROJECT_MEMBER(NO, PRJ_KEY, EMP_NO, MODI_AUTH) VALUES (SEQ_PROJECT_MEMBER.NEXTVAL, '0002', 240106, '수정');
INSERT INTO PROJECT_MEMBER(NO, PRJ_KEY, EMP_NO, MODI_AUTH) VALUES (SEQ_PROJECT_MEMBER.NEXTVAL, '0002', 240102, '읽기');
INSERT INTO PROJECT_MEMBER(NO, PRJ_KEY, EMP_NO, MODI_AUTH) VALUES (SEQ_PROJECT_MEMBER.NEXTVAL, '0003', 240102, '수정');
INSERT INTO PROJECT_MEMBER(NO, PRJ_KEY, EMP_NO, MODI_AUTH) VALUES (SEQ_PROJECT_MEMBER.NEXTVAL, '0004', 240102, '수정');
INSERT INTO PROJECT_MEMBER(NO, PRJ_KEY, EMP_NO, MODI_AUTH) VALUES (SEQ_PROJECT_MEMBER.NEXTVAL, '0004', 240103, '수정');
INSERT INTO PROJECT_MEMBER(NO, PRJ_KEY, EMP_NO, MODI_AUTH) VALUES (SEQ_PROJECT_MEMBER.NEXTVAL, '0004', 240104, '읽기');

--------------------------------------------------------------------------------
---------------------------- PROJECT-MEMO --------------------------------------
--------------------------------------------------------------------------------
INSERT INTO PRJ_MEMO(NO, PRJ_KEY, WRITER_NO, BP_NO, ST_NO, PRIORITY, NAME, CONTENT, ING, START_DATE, END_DATE) VALUES ( SEQ_PRJ_MEMO.NEXTVAL, '0001', '240101', '1', '1' , '1' , '제목1', '텃', '진행대기', '20241101', '20241120');
INSERT INTO PRJ_MEMO(NO, PRJ_KEY, WRITER_NO, BP_NO, ST_NO, PRIORITY, NAME, CONTENT, ING, START_DATE, END_DATE) VALUES ( SEQ_PRJ_MEMO.NEXTVAL, '0001', '240101', '2', '1' , '1' , '제목2', '텃밭', '진행대기', '20241102', '20241121');
INSERT INTO PRJ_MEMO(NO, PRJ_KEY, WRITER_NO, BP_NO, ST_NO, PRIORITY, NAME, CONTENT, ING, START_DATE, END_DATE) VALUES ( SEQ_PRJ_MEMO.NEXTVAL, '0001', '240101', '3', '1' , '1' , '제목3', '텃밭에', '진행중', '20241103', '20241122');
INSERT INTO PRJ_MEMO(NO, PRJ_KEY, WRITER_NO, BP_NO, ST_NO, PRIORITY, NAME, CONTENT, ING, START_DATE, END_DATE) VALUES ( SEQ_PRJ_MEMO.NEXTVAL, '0001', '240101',  '4','1' , '1' , '제목4', '텃밭에다', '진행중', '20241104', '20241123');
INSERT INTO PRJ_MEMO(NO, PRJ_KEY, WRITER_NO, BP_NO, ST_NO, PRIORITY, NAME, CONTENT, ING, START_DATE, END_DATE) VALUES ( SEQ_PRJ_MEMO.NEXTVAL, '0001', '240101',  '5','1' , '1' , '제목5', '텃밭에다가', '진행중', '20241105', '20241124');
INSERT INTO PRJ_MEMO(NO, PRJ_KEY, WRITER_NO, BP_NO, ST_NO, PRIORITY, NAME, CONTENT, ING, START_DATE, END_DATE) VALUES ( SEQ_PRJ_MEMO.NEXTVAL, '0002',  '240101', '2','1' , '2' , '제목6', '텃밭에다가 감', '진행완료', '20241106', '20241125');
INSERT INTO PRJ_MEMO(NO, PRJ_KEY, WRITER_NO, BP_NO, ST_NO, PRIORITY, NAME, CONTENT, ING, START_DATE, END_DATE) VALUES ( SEQ_PRJ_MEMO.NEXTVAL, '0002',  '240101','1', '1' , '2' , '제목7', '텃밭에다가 감자', '진행완료', '20241107', '20241126');
INSERT INTO PRJ_MEMO(NO, PRJ_KEY, WRITER_NO, BP_NO, ST_NO, PRIORITY, NAME, CONTENT, ING, START_DATE, END_DATE) VALUES ( SEQ_PRJ_MEMO.NEXTVAL, '0002',  '240101','1', '1' , '3' , '제목8', '텃밭에다가 감자심', '진행완료', '20241101', '20241122');
INSERT INTO PRJ_MEMO(NO, PRJ_KEY, WRITER_NO, BP_NO, ST_NO, PRIORITY, NAME, CONTENT, ING, START_DATE, END_DATE) VALUES ( SEQ_PRJ_MEMO.NEXTVAL, '0003',  '240101','1', '1' , '3' , '제목9', '텃밭에다가 감자심기', '진행완료', '20241101', '20241122');
INSERT INTO PRJ_MEMO(NO, PRJ_KEY, WRITER_NO, BP_NO, ST_NO, PRIORITY, NAME, CONTENT, ING, START_DATE, END_DATE) VALUES ( SEQ_PRJ_MEMO.NEXTVAL, '0004','240101', '1',  '1' , '3' , '감자심기', ' 감자', '진행완료', '20241101', '20241122');

--------------------------------------------------------------------------------
----------------------------- MEMO-MEMBER --------------------------------------
--------------------------------------------------------------------------------
INSERT INTO MEMO_MEMBER( NO, MEMO_KEY, EMP_NO, MODI_AUTH) VALUES ( SEQ_MEMO_MEMBER.NEXTVAL, '1', '240102', '읽기');
INSERT INTO MEMO_MEMBER( NO, MEMO_KEY, EMP_NO, MODI_AUTH) VALUES ( SEQ_MEMO_MEMBER.NEXTVAL, '1', '240103', '읽기');
INSERT INTO MEMO_MEMBER( NO, MEMO_KEY, EMP_NO, MODI_AUTH) VALUES ( SEQ_MEMO_MEMBER.NEXTVAL, '1', '240104', '수정');
INSERT INTO MEMO_MEMBER( NO, MEMO_KEY, EMP_NO, MODI_AUTH) VALUES ( SEQ_MEMO_MEMBER.NEXTVAL, '1', '240105', '수정');
INSERT INTO MEMO_MEMBER( NO, MEMO_KEY, EMP_NO, MODI_AUTH) VALUES ( SEQ_MEMO_MEMBER.NEXTVAL, '2', '240106', '수정');
INSERT INTO MEMO_MEMBER( NO, MEMO_KEY, EMP_NO, MODI_AUTH) VALUES ( SEQ_MEMO_MEMBER.NEXTVAL, '2', '240107', '읽기');
INSERT INTO MEMO_MEMBER( NO, MEMO_KEY, EMP_NO, MODI_AUTH) VALUES ( SEQ_MEMO_MEMBER.NEXTVAL, '2', '240108', '읽기');
INSERT INTO MEMO_MEMBER( NO, MEMO_KEY, EMP_NO, MODI_AUTH) VALUES ( SEQ_MEMO_MEMBER.NEXTVAL, '3', '240109', '읽기');

--------------------------------------------------------------------------------
---------------------------------- ADMIN ---------------------------------------
--------------------------------------------------------------------------------
INSERT INTO ADMIN (NICK, CP_CODE, ID, PWD) VALUES ('관리자', 'A001', 'ADMIN', '9999');

--------------------------------------------------------------------------------
----------------------------------- DEPT ---------------------------------------
--------------------------------------------------------------------------------
INSERT INTO DEPT (DEPT_CODE, DEPT_NAME) VALUES (SEQ_DEPT.NEXTVAL, '영업부');
INSERT INTO DEPT (DEPT_CODE, DEPT_NAME) VALUES (SEQ_DEPT.NEXTVAL, '관리부');
INSERT INTO DEPT (DEPT_CODE, DEPT_NAME) VALUES (SEQ_DEPT.NEXTVAL, '마케팅부');
INSERT INTO DEPT (DEPT_CODE, DEPT_NAME) VALUES (SEQ_DEPT.NEXTVAL, '개발부');
INSERT INTO DEPT (DEPT_CODE, DEPT_NAME) VALUES (SEQ_DEPT.NEXTVAL, 'CS부');
INSERT INTO DEPT (DEPT_CODE, DEPT_NAME) VALUES (SEQ_DEPT.NEXTVAL, '생산부');
INSERT INTO DEPT (DEPT_CODE, DEPT_NAME) VALUES (SEQ_DEPT.NEXTVAL, '인사부');
INSERT INTO DEPT (DEPT_CODE, DEPT_NAME) VALUES (SEQ_DEPT.NEXTVAL, '재무부');
INSERT INTO DEPT (DEPT_CODE, DEPT_NAME) VALUES (SEQ_DEPT.NEXTVAL, '총무부');
INSERT INTO DEPT (DEPT_CODE, DEPT_NAME) VALUES (SEQ_DEPT.NEXTVAL, '기획부');
INSERT INTO DEPT (DEPT_CODE, DEPT_NAME) VALUES (SEQ_DEPT.NEXTVAL, '법무부');
INSERT INTO DEPT (DEPT_CODE, DEPT_NAME) VALUES (SEQ_DEPT.NEXTVAL, '홍보부');
INSERT INTO DEPT (DEPT_CODE, DEPT_NAME) VALUES (SEQ_DEPT.NEXTVAL, 'IT부');
INSERT INTO DEPT (DEPT_CODE, DEPT_NAME) VALUES (SEQ_DEPT.NEXTVAL, '물류부');

--------------------------------------------------------------------------------
----------------------------------- JOB ---------------------------------------
--------------------------------------------------------------------------------
INSERT INTO JOB (JOB_CODE, JOB_NAME) VALUES (SEQ_JOB.NEXTVAL, '사원');
INSERT INTO JOB (JOB_CODE, JOB_NAME) VALUES (SEQ_JOB.NEXTVAL, '대리');
INSERT INTO JOB (JOB_CODE, JOB_NAME) VALUES (SEQ_JOB.NEXTVAL, '과장');
INSERT INTO JOB (JOB_CODE, JOB_NAME) VALUES (SEQ_JOB.NEXTVAL, '차장');
INSERT INTO JOB (JOB_CODE, JOB_NAME) VALUES (SEQ_JOB.NEXTVAL, '부장');
INSERT INTO JOB (JOB_CODE, JOB_NAME) VALUES (SEQ_JOB.NEXTVAL, '임원');

--------------------------------------------------------------------------------
----------------------------------- COMPANY ------------------------------------
--------------------------------------------------------------------------------
INSERT INTO COMPANY(CP_CODE,CP_NAME) VALUES ('A' || LPAD(SEQ_COMPANY.NEXTVAL, 3, '0'),'요리조리');

--------------------------------------------------------------------------------
------------------------------------ MEMBER ------------------------------------
--------------------------------------------------------------------------------
INSERT INTO EMPLOYEE (CP_CODE, JOB_CODE, DEPT_CODE) VALUES ('A001', 2, 8);
INSERT INTO MEMBER (NO, ID, NAME, PWD, ID_NUM, GENDER, PHONE, EMAIL, ADDRESS) 
VALUES (SEQ_MEMBER.NEXTVAL, (SELECT MAX(EMP_NO) FROM EMPLOYEE), '정지아', '800901', '8009012026819', 'F', '01063324755', 'em@company.com', '성남');

INSERT INTO EMPLOYEE (CP_CODE, JOB_CODE, DEPT_CODE) VALUES ('A001', 3, 8);
INSERT INTO MEMBER (NO, ID, NAME, PWD, ID_NUM, GENDER, PHONE, EMAIL, ADDRESS) 
VALUES (SEQ_MEMBER.NEXTVAL, (SELECT MAX(EMP_NO) FROM EMPLOYEE), '임도윤', '890720', '8907201289139', 'M', '01045859182', 'employee2@company.com', '서울 강남구 ');

INSERT INTO EMPLOYEE (CP_CODE, JOB_CODE, DEPT_CODE) VALUES ('A001', 5, 13);
INSERT INTO MEMBER (NO, ID, NAME, PWD, ID_NUM, GENDER, PHONE, EMAIL, ADDRESS)
VALUES (SEQ_MEMBER.NEXTVAL, (SELECT MAX(EMP_NO) FROM EMPLOYEE), '조수현', '010126', '0101264573117', 'F', '01059229140', 'employee3@company.com', '의정부');

INSERT INTO EMPLOYEE (CP_CODE, JOB_CODE, DEPT_CODE) VALUES ('A001', 2, 3);
INSERT INTO MEMBER (NO, ID, NAME, PWD, ID_NUM, GENDER, PHONE, EMAIL, ADDRESS)
VALUES (SEQ_MEMBER.NEXTVAL, (SELECT MAX(EMP_NO) FROM EMPLOYEE), '최지훈', '000105', '0001053078869', 'M', '01060421700', 'employee4@company.com', '대전 성심당');

INSERT INTO EMPLOYEE (CP_CODE, JOB_CODE, DEPT_CODE) VALUES ('A001', 5, 14);
INSERT INTO MEMBER (NO, ID, NAME, PWD, ID_NUM, GENDER, PHONE, EMAIL, ADDRESS) 
VALUES (SEQ_MEMBER.NEXTVAL, (SELECT MAX(EMP_NO) FROM EMPLOYEE), '임서준', '890121', '8901211352445', 'M', '01017749625', 'employee5@company.com', '서울 역삼동 KH');

INSERT INTO EMPLOYEE (CP_CODE, JOB_CODE, DEPT_CODE) VALUES ('A001', 6, 6);
INSERT INTO MEMBER (NO, ID, NAME, PWD, ID_NUM, GENDER, PHONE, EMAIL, ADDRESS) 
VALUES (SEQ_MEMBER.NEXTVAL, (SELECT MAX(EMP_NO) FROM EMPLOYEE), '윤민지', '950109', '9501092707872', 'F', '01072718942', 'employee6@company.com', '경기도 남양주');
