--------------------------------------------------------------------------------
---------------------------------- SEQUENCE ------------------------------------
--------------------------------------------------------------------------------
DROP SEQUENCE SEQ_STORE;
CREATE SEQUENCE SEQ_STORE NOCACHE NOCYCLE;

DROP SEQUENCE SEQ_ST_ATTACHMENT;
CREATE SEQUENCE SEQ_ST_ATTACHMENT NOCACHE NOCYCLE;

DROP SEQUENCE SEQ_BUSINESS;
CREATE SEQUENCE SEQ_BUSINESS NOCACHE NOCYCLE;

DROP SEQUENCE SEQ_BP_ATTACHMENT;
CREATE SEQUENCE SEQ_BP_ATTACHMENT NOCACHE NOCYCLE;

DROP SEQUENCE SEQ_BUSINESS_HISTORY;
CREATE SEQUENCE SEQ_BUSINESS_HISTORY NOCACHE NOCYCLE;

--------------------------------------------------------------------------------
---------------------------------- FUCTION -------------------------------------
--------------------------------------------------------------------------------
-- BUSINESS FUNCTION
CREATE OR REPLACE FUNCTION GET_BP_ATTACHMENT_NO
RETURN NUMBER
AS
    N NUMBER;
BEGIN
    SELECT SEQ_BP_ATTACHMENT.NEXTVAL
    INTO N
    FROM DUAL;
    RETURN N;
END
;
/

-- STORE FUNCTION
CREATE OR REPLACE FUNCTION GET_ST_ATTACHMENT_NO
RETURN NUMBER
AS
    N NUMBER;
BEGIN
    SELECT SEQ_ST_ATTACHMENT.NEXTVAL
    INTO N
    FROM DUAL;
    RETURN N;
END
;
/

--------------------------------------------------------------------------------
-------------------------- TABLE CREATE & DROP ---------------------------------
--------------------------------------------------------------------------------
DROP TABLE STORE CASCADE CONSTRAINTS;
CREATE TABLE STORE (
NO	        NUMBER		                NOT NULL PRIMARY KEY,
MANAGER_NO	NUMBER		                NOT NULL,
NAME	    VARCHAR2(30)		        NOT NULL,
CEO	        VARCHAR2(30)	        	NOT NULL,
BRN	        CHAR(10)		            NOT NULL,
START_DATE	CHAR(8)	                	NULL,
END_DATE	CHAR(8)	                	NULL,
ADDRESS	VARCHAR2(250)	        	NULL,
PHONE	    VARCHAR2(15)	          	NULL,
CEO_PHONE	CHAR(11)            		NULL,
DEL_YN	    CHAR(1)	    DEFAULT 'N' 	CHECK(DEL_YN IN('Y','N')),
ENROLL_DATE	TIMESTAMP	DEFAULT SYSDATE	NULL,
MODIFY_DATE	TIMESTAMP		            NULL,
EDU_DATE	CHAR(12)	            	NULL,
OPEN_DATE	CHAR(8)	                	NULL,
STATUS      VARCHAR2(20)                NULL,
CLOSE_DATE  CHAR(8)     DEFAULT '-'     NULL
);

DROP TABLE ST_ATTACHMENT CASCADE CONSTRAINTS;
CREATE TABLE ST_ATTACHMENT (
NO	        NUMBER		                NULL PRIMARY KEY,
REF_ST_NO	NUMBER		                NOT NULL,
ORIGIN_NAME	VARCHAR2(2000)		        NULL,
CHANGE_NAME	VARCHAR2(2000)      		NULL,
FILE_PATH	VARCHAR2(2000)	        	NULL,
STATUS	    CHAR(1) 	DEFAULT 'Y' 	NULL,
ENROLL_DATE	TIMESTAMP	DEFAULT SYSDATE	NULL
);

DROP TABLE BUSINESS CASCADE CONSTRAINTS;
CREATE TABLE BUSINESS (
NO	        NUMBER		                NOT NULL PRIMARY KEY,
MANAGER_NO	NUMBER	                	NOT NULL,
DEPT_NAME   VARCHAR(30)                 NOT NULL,
NAME	    VARCHAR2(30)	        	NOT NULL,
CEO	        VARCHAR2(20)        		NOT NULL,
BRN	        CHAR(10)            		NOT NULL,
BT_CODE	    CHAR(6)	                	NULL,
ADDRESS	    VARCHAR2(250)	        	NOT NULL,
PHONE	    CHAR(11)	            	NOT NULL,
DEL_YN	    CHAR(1)	    DEFAULT 'N' 	CHECK(DEL_YN IN('Y','N')),
ENROLL_DATE	TIMESTAMP	DEFAULT SYSDATE	NULL,
MODIFY_DATE	TIMESTAMP		            NULL
);

DROP TABLE BP_ATTACHMENT CASCADE CONSTRAINTS;
CREATE TABLE BP_ATTACHMENT (
NO      	NUMBER		                NULL PRIMARY KEY,
REF_BP_NO	NUMBER		                NOT NULL,
ORIGIN_NAME	VARCHAR2(2000)	        	NULL,
CHANGE_NAME	VARCHAR2(2000)	        	NULL,
FILE_PATH	VARCHAR2(2000)	        	NULL,
STATUS	    CHAR(1)	    DEFAULT 'Y'	    NULL,
ENROLL_DATE	TIMESTAMP	DEFAULT SYSDATE	NULL
);

DROP TABLE BUSINESS_HISTORY CASCADE CONSTRAINTS;
CREATE TABLE BUSINESS_HISTORY (
NO          NUMBER                      NOT NULL PRIMARY KEY,
BP_NO       NUMBER                      NOT NULL,
START_DATE  CHAR(8)                     NOT NULL,
END_DATE    CHAR(8)                     NULL
);

--------------------------------------------------------------------------------
--------------------------------- COMMENT --------------------------------------
--------------------------------------------------------------------------------
COMMENT ON COLUMN BP_ATTACHMENT.NO IS '거래처첨부고유번호';
COMMENT ON COLUMN BP_ATTACHMENT.REF_BP_NO IS '거래처번호';
COMMENT ON COLUMN BP_ATTACHMENT.ORIGIN_NAME IS '원본파일명';
COMMENT ON COLUMN BP_ATTACHMENT.CHANGE_NAME IS '수정파일명';
COMMENT ON COLUMN BP_ATTACHMENT.FILE_PATH IS '파일경로';
COMMENT ON COLUMN BP_ATTACHMENT.STATUS IS '파일상태';
COMMENT ON COLUMN BP_ATTACHMENT.ENROLL_DATE IS '업로드일시';

COMMENT ON COLUMN BUSINESS_HISTORY.NO IS '거래고유번호';
COMMENT ON COLUMN BUSINESS_HISTORY.BP_NO IS '거래처 번호';
COMMENT ON COLUMN BUSINESS_HISTORY.START_DATE IS '거래시작일';
COMMENT ON COLUMN BUSINESS_HISTORY.END_DATE IS '거래종료일';

COMMENT ON COLUMN BUSINESS.NO IS '거래처 번호';
COMMENT ON COLUMN BUSINESS.MANAGER_NO IS '담당자 사번';
COMMENT ON COLUMN BUSINESS.NAME IS '거래처명';
COMMENT ON COLUMN BUSINESS.CEO IS '대표자명';
COMMENT ON COLUMN BUSINESS.BRN IS '사업자등록번호';
COMMENT ON COLUMN BUSINESS.BT_CODE IS '업태코드';
COMMENT ON COLUMN BUSINESS.ADDRESS IS '거래처 주소';
COMMENT ON COLUMN BUSINESS.PHONE IS '거래처 전화번호';
COMMENT ON COLUMN BUSINESS.DEL_YN IS '삭제여부';
COMMENT ON COLUMN BUSINESS.ENROLL_DATE IS '작성일';
COMMENT ON COLUMN BUSINESS.MODIFY_DATE IS '수정일';

COMMENT ON COLUMN STORE.NO IS '가맹점 번호';
COMMENT ON COLUMN STORE.MANAGER_NO IS '담당자 사번';
COMMENT ON COLUMN STORE.NAME IS '가맹점명';
COMMENT ON COLUMN STORE.CEO IS '가맹점주명';
COMMENT ON COLUMN STORE.BRN IS '사업자등록번호';
COMMENT ON COLUMN STORE.START_DATE IS '계약 시작일';
COMMENT ON COLUMN STORE.END_DATE IS '계약 종료일';
COMMENT ON COLUMN STORE.ADDRESS IS '가맹점 주소';
COMMENT ON COLUMN STORE.PHONE IS '가맹점 전화번호';
COMMENT ON COLUMN STORE.CEO_PHONE IS '가맹점장 전화번호';
COMMENT ON COLUMN STORE.DEL_YN IS '가맹점 삭제여부';
COMMENT ON COLUMN STORE.ENROLL_DATE IS '작성일';
COMMENT ON COLUMN STORE.MODIFY_DATE IS '수정일';
COMMENT ON COLUMN STORE.EDU_DATE IS '교육일자';
COMMENT ON COLUMN STORE.OPEN_DATE IS '오픈일';
COMMENT ON COLUMN STORE.CLOSE_DATE IS '폐업일';
COMMENT ON COLUMN STORE.STATUS IS '오픈 상태';

COMMENT ON COLUMN ST_ATTACHMENT.NO IS '가맹점첨부고유번호';
COMMENT ON COLUMN ST_ATTACHMENT.REF_ST_NO IS '가맹점 번호';
COMMENT ON COLUMN ST_ATTACHMENT.ORIGIN_NAME IS '원본파일명';
COMMENT ON COLUMN ST_ATTACHMENT.CHANGE_NAME IS '수정파일명';
COMMENT ON COLUMN ST_ATTACHMENT.FILE_PATH IS '파일경로';
COMMENT ON COLUMN ST_ATTACHMENT.STATUS IS '파일상태';
COMMENT ON COLUMN ST_ATTACHMENT.ENROLL_DATE IS '업로드일시';

--------------------------------------------------------------------------------
------------------------------- FOREIGN KEY ------------------------------------
--------------------------------------------------------------------------------
ALTER TABLE BUSINESS_HISTORY ADD CONSTRAINT FK_BUSINESS_TO_BUSINESS_HISTORY_1 FOREIGN KEY (BP_NO) REFERENCES BUSINESS (NO);
ALTER TABLE BUSINESS ADD CONSTRAINT FK_EMPLOYEE_TO_BUSINESS_1 FOREIGN KEY (MANAGER_NO) REFERENCES EMPLOYEE (EMP_NO);
ALTER TABLE BP_ATTACHMENT ADD CONSTRAINT FK_BUSINESS_TO_BP_ATTACHMENT_1 FOREIGN KEY (REF_BP_NO) REFERENCES BUSINESS (NO);
ALTER TABLE ST_ATTACHMENT ADD CONSTRAINT FK_STORE_TO_ST_ATTACHMENT_1 FOREIGN KEY (REF_ST_NO) REFERENCES STORE (NO);
ALTER TABLE STORE ADD CONSTRAINT FK_EMPLOYEE_TO_STORE_1 FOREIGN KEY (MANAGER_NO) REFERENCES EMPLOYEE (EMP_NO);

